info:
  title: "My Project"
  repository_url: "https://github.com/myproject"

filters:
  tags:
    exclude:
      - "v0.1.*"

sort:
  by: "tag"
  order: "desc"

groupBy:
  type: "tag"
  commitsSort:
    by: "subject"
    order: "asc"

template: |
  {{range .Versions}}
  ## {{.Tag.Name}} ({{datetime "2006-01-02" .Date}})
  {{range .CommitGroups}}
  ### {{.Title}}
  {{range .Commits}}
  - {{.Subject█

