name: Update Changelog
on:
  push:
    branches: [main]
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update txt
        run: |
          sed -i 's/test/test1/g' test.txt
      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'youremail@example.com'          
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
